const styles = {
  custom_container: "w-11/12 hidden sm:block",
  // heading: "text-[27px] text-center md:text-start font-[600] font-Roboto pb-[20px]",
  heading: "text-2xl md:text-3xl font-semibold tracking-tight text-foreground text-center md:text-start pb-5",  
  section: "w-11/12 mx-auto",
  // productTitle: "text-[25px] font-[600] font-Roboto text-[#333]",
  // productDiscountPrice: "font-bold text-[18px] text-[#333] font-Roboto",
  // price: "font-[500] text-[16px] text-[#d55b54] pl-2 line-through",
  // shop_name: "pt-3 text-[15px] text-blue-400 pb-0.5",
  // active_indicator: "absolute bottom-[-5px] left-0 h-[3px] w-full bg-[crimson]",
  // button: "w-[150px] bg-black h-[50px] my-3 flex items-center justify-center rounded-xl cursor-pointer",
  // submit_button: "group relative w-full h-[40px] flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700",
   productTitle: "text-xl font-semibold text-foreground",
  productDiscountPrice: "font-bold text-lg text-foreground",
  price: "font-medium text-sm text-muted-foreground pl-2 line-through",
  shop_name: "pt-3 text-sm text-primary hover:underline pb-0.5",
  active_indicator: "absolute bottom-[-5px] left-0 h-0.75 w-full bg-accent rounded-full",
  button: "min-w-37.5 px-6 bg-primary hover:bg-primary-hover text-primary-foreground h-12.5 my-3 flex items-center justify-center rounded-lg cursor-pointer transition-colors shadow-sm",
  submit_button: "group relative w-full h-11 flex items-center justify-center gap-2 px-4 border border-transparent text-sm font-medium rounded-md text-primary-foreground bg-primary hover:bg-primary-hover transition-colors",  
  cart_button: "px-5 h-9.5 rounded-full bg-accent hover:bg-accent-hover flex items-center justify-center cursor-pointer transition-colors",
  cart_button_text: "text-accent-foreground text-[15px] font-semibold",
  // input: "w-full border p-1 rounded-[5px]",
  input: "appearance-none block w-full px-3 py-2 border border-border bg-surface text-foreground rounded-md shadow-xs placeholder-muted-foreground focus:outline-none focus:ring-2 focus:ring-focus-ring focus:border-primary sm:text-sm",  
  activeStatus: "w-2.5 h-2.5 rounded-full bg-success inline-block mr-2",
  normalFlex: "flex items-center",
};

export default styles;